PMR: First Release!
Update to pmr_ase_del1.

Signed-off-by: John Jacques <john.jacques@intel.com>

diff --git a/yocto_build/Makefile b/yocto_build/Makefile
--- a/yocto_build/Makefile
+++ b/yocto_build/Makefile
@@ -18,47 +18,58 @@
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 # THE SOFTWARE.
 #
-# Authors: behlul.sutarwala@intel.com
+# Authors: sudhir.gopal@intel.com
 #
-# Makefile for AXXIA Yocto Build
+# Makefile for Yocto Build
 
 TOP                     ?= $(shell pwd)
 SHELL                    = /bin/bash
 BLDDIR                  ?= $(TOP)/axxia
-BB_IMAGE_TYPE           ?= axxia-image-sim
-RDK_SRC_PATH            ?= $(TOP)
-RDK_KLM_ARCHIVE         ?= rdk_klm_src.txz
-RDK_TOOLS_ARCHIVE       ?= rdk_user_src.txz
-SIMICS_FILE             ?= $(TOP)/simics*
-BB_NUMBER_THREADS       ?= "24"
-PARALLEL_MAKE           := "-j $(BB_NUMBER_THREADS)"
-INCLUDE_RDK             ?= true
-INCLUDE_RDK_TOOLS       ?= true
-INCLUDE_SIMICSFS        ?= true
-SIMICS_VERSION          ?= 6.0.96_del4
-META_AXXIA_REL          ?= grr_ase_rdk_del4
-RDK_KLM_VERSION         ?= grr_del4
-RDK_TOOLS_VERSION       ?= grr_del4
-DL_DIR                  ?=
+BB_IMAGE_TYPE           ?= axxia-image-run
+BB_MACHINE_NAME         ?= intel-axxia-pmr
 BB_NO_NETWORK           ?= 0
-RDK_MODULES_STATIC      ?= false
-IES_ENABLE_SHM          ?= true
+BB_NUMBER_THREADS       ?= "24"
+DL_DIR                  ?=
+IES_ENABLE_SHM          := false
+INCLUDE_RDK             ?= false
+INCLUDE_RDK_TOOLS       ?= false
+INCLUDE_SIMICSFS        ?= true
+LINUX_VERSION           ?= v6.9
+LINUX_CONF              ?= $(TOP)/linux.conf
+PARALLEL_MAKE           := "-j $(BB_NUMBER_THREADS)"
+META_AXXIA_REL          ?= pmr_ase_del1
+RDK_KLM_VERSION         ?= pmr_del1
+RDK_TOOLS_VERSION       ?= pmr_del1
 RDK_LTTNG_ENABLE        ?= false
+INCLUDE_UPDATES         ?= false
+RDK_KLM_ARCHIVE         ?= rdk_klm_src.tgz
+RDK_MODULES_STATIC      ?= false
+RDK_SRC_PATH            ?= $(TOP)
+RDK_TOOLS_ARCHIVE       ?= rdk_user_src.tgz
+USE_RDK_REPO            ?= false
+RDK_REPO                ?= https://github.com/intel-collab/networking.wireless.ran.bts-rdk-releases
+SIMICS_FILE             ?= $(TOP)/simics*
+SIMICS_VERSION          ?= 7.15.0
 
-LINUX_VERSION           ?= 5.10
-PREFERRED_VERSION_linux            = "PREFERRED_VERSION_linux-intel"
-PREFERRED_PROVIDER_virtual/kernel := "linux-intel"
-ifeq (,$(filter $(LINUX_VERSION),5.10))
-  $(error LINUX_VERSION is not set correctly, run 'make help' for usage)
+PREFERRED_PROVIDER_virtual/kernel   := "linux-korg"
+KORG_VERSION                         = $(LINUX_VERSION)
+
+ifeq (,$(filter $(LINUX_VERSION),v6.9))
+    $(error LINUX_VERSION is not set correctly, run 'make help' for usage)
 endif
 
-META_AXXIA_DEPENDENCY               ?= $(TOP)/meta-intel-axxia/DEPENDENCIES.vcn
+ifeq ($(wildcard $(LINUX_CONF)),)
+    $(error LINUX_CONF needs to point to a valid Linux configuration file)
+endif
+
+META_AXXIA_DEPENDENCY               ?= $(TOP)/meta-intel-axxia/DEPENDENCIES.distro
 DISTRO                              := "intel-axxia"
-RUNTARGET                           := "snr"
+RUNTARGET                           := "vcn"
 DISTRO_FEATURES_append_intree       := " rdk-userspace"
 
-AXXIA_REPO_NAME                     := meta-intel-axxia/meta-intel-vcn
+AXXIA_REPO_NAME                     := meta-intel-axxia/meta-intel-distro
 RDK_REPO_NAME                       := meta-intel-axxia/meta-intel-rdk
+UPDATES_REPO_NAME                   := meta-intel-axxia-updates
 
 # Define V=1 to echo everything
 V ?= 1
@@ -71,28 +82,37 @@ RM = $(Q)rm -f
 META_AXXIA_URL   ?= https://github.com/axxia/meta-intel-axxia.git
 LAYERS           += $(TOP)/meta-intel-axxia
 
-POKY_URL      = https://git.yoctoproject.org/git/poky
-LAYERS       += $(TOP)/poky
+POKY_URL          = https://git.yoctoproject.org/poky
+LAYERS           += $(TOP)/poky
 
-OE_URL        = https://github.com/openembedded/meta-openembedded.git
-LAYERS       += $(TOP)/meta-openembedded
+OE_URL            = https://github.com/openembedded/meta-openembedded.git
+LAYERS           += $(TOP)/meta-openembedded
 
-VIRT_URL      = https://git.yoctoproject.org/git/meta-virtualization
-LAYERS       += $(TOP)/meta-virtualization
+VIRT_URL          = https://git.yoctoproject.org/meta-virtualization
+LAYERS           += $(TOP)/meta-virtualization
 
-INTEL_URL     = https://git.yoctoproject.org/git/meta-intel
-LAYERS       += $(TOP)/meta-intel
+INTEL_URL         = https://git.yoctoproject.org/meta-intel
+LAYERS           += $(TOP)/meta-intel
 
-SECURITY_URL  = https://git.yoctoproject.org/git/meta-security
-LAYERS       += $(TOP)/meta-security
+SECURITY_URL      = https://git.yoctoproject.org/meta-security
+LAYERS           += $(TOP)/meta-security
 
-META_ROS      = https://github.com/bmwcarit/meta-ros.git
-LAYERS       += $(TOP)/meta-ros
+META_ROS          = https://github.com/bmwcarit/meta-ros.git
+LAYERS           += $(TOP)/meta-ros
+
+META_UPDATES_URL ?= https://github.com/axxia/meta-intel-axxia-updates.git
+LAYERS           += $(TOP)/meta-intel-axxia-updates
+
+define source-bb-env
+	cd $(TOP)/meta-intel-axxia               ; \
+	source meta-intel-distro/axxia-env       ; \
+	cd $(TOP)/poky                           ; \
+	source oe-init-build-env $(BLDDIR)
+endef
 
 define bitbake
 	set -e ; \
-	cd $(TOP)/poky ; \
-	source oe-init-build-env $(BLDDIR) ; \
+	$(call source-bb-env) ; \
 	echo BLDDIR=$(BLDDIR) ; \
 	cd $(BLDDIR) ; \
 	bitbake -c cleanall $(1) ; \
@@ -101,16 +121,14 @@ endef
 
 define bitbake-task
 	set -e ; \
-	cd $(TOP)/poky ; \
-	source oe-init-build-env $(BLDDIR) ; \
+	$(call source-bb-env) ; \
 	cd $(BLDDIR) ; \
 	bitbake $(1) -c $(2)
 endef
 
 define bitbake-cleansstate
 	set -e ; \
-        cd $(TOP)/poky ; \
-        source oe-init-build-env $(BLDDIR) ; \
+	$(call source-bb-env) ; \
 	cd $(BLDDIR) ; \
 	CLEAN_TARGETS="virtual/kernel $(1)" ; \
 	if [[ "$(INCLUDE_SIMICSFS)" = "true" ]]; then CLEAN_TARGETS="$$CLEAN_TARGETS simicsfs-client" ; fi ; \
@@ -131,6 +149,16 @@ define populate
             git clean -dfx; \
 	    git fetch --all -f ; \
 	fi;
+endef
+
+#
+# Default to main if branch not available.
+#
+define checkout_rev_main
+	set -e ; \
+	(git -C $(1) show-branch origin/$(2) &>/dev/null) && \
+		(git -C $(1) checkout $(2)) || \
+		(git -C $(1) checkout main)
 endef
 
 define checkout_rev
@@ -184,7 +212,9 @@ help:
 	echo "META_AXXIA_URL=<URL-for-meta-intel-axxia>: Optional:"; \
 	echo "    Defaults to https://github.com/axxia/meta-intel-axxia.git"; \
 	echo "META_AXXIA_DEPENDENCY=<File which contains commit ids of meta layers>: Optional:"; \
-	echo "    Defaults to <current-dir>/meta-intel-axxia/DEPENDENCIES.vcn"; \
+	echo "    Defaults to <current-dir>/meta-intel-axxia/DEPENDENCIES.distro"; \
+	echo "LINUX_CONF: Required" ; \
+	echo "    Points to the location of the linux.conf file for the kernel" ; \
 	echo "INCLUDE_RDK: Optional: Default = true:" ; \
 	echo "    When set to 'true', builds RDK in-tree,"; \
 	echo "    Set to 'false' to only build Linux"; \
@@ -193,25 +223,39 @@ help:
 	echo "    When set to 'true', builds RDK userspace tools,"; \
 	echo "    Set to 'false' build RDK in-tree without rdk-tools"; \
 	echo "INCLUDE_SIMICSFS: Optional: Default = true:" ; \
-	echo "    When set to 'true', builds with simicsfs,"; \
-	echo "    Set to 'false' builds Linux without simicsfs"; \
+	echo "    When set to 'true', builds with simics,"; \
+	echo "    Set to 'false' builds Linux without simics"; \
 	echo "RDK_SRC_PATH=<Location-of-RDK-Archives>"; \
 	echo "    Required: when INCLUDE_RDK='true'"; \
 	echo "    Default:  <current-dir>"; \
 	echo "RDK_KLM_ARCHIVE=<Name-of-RDK-KLM-Archive>"; \
 	echo "    Required: when INCLUDE_RDK='true'"; \
-	echo "    Default:  <current-dir>/rdk_klm_src.txz"; \
+	echo "    Default:  <current-dir>/rdk_klm_src.tgz"; \
 	echo "RDK_TOOLS_ARCHIVE=<Name-of-RDK-USERSPACE-TOOLS-Archive>"; \
 	echo "    Required: when INCLUDE_RDK='true' and INCLUDE_RDK_TOOLS='true'"; \
-	echo "    Default:  <current-dir>/rdk_user_src.txz"; \
+	echo "    Default:  <current-dir>/rdk_user_src.tgz"; \
+	echo "USE_RDK_REPO: Optional: Default = false:"; \
+	echo "    When set to 'true', get RDK sources from a git repository."; \
+	echo "    Depends on INCLUDE_RDK=true"; \
+	echo "    Special access permissions from Intel are required to be able to fetch"; \
+	echo "    RDK sources from the Intel GitHub repositories."; \
+	echo "RDK_REPO=<RDK-Git-repository>:"; \
+	echo "    Required: when USE_RDK_REPO='true'"; \
+	echo "    Defaults to https://github.com/intel-collab/networking.wireless.ran.bts-rdk-releases"; \
+	echo "    Depends on INCLUDE_RDK=true and USE_RDK_REPO=true"; \
+	echo "RDK_REPO_REV=<tag/commit>:"; \
+	echo "    Required: when USE_RDK_REPO='true'"; \
+	echo "    Should contain the git revision (tag or commit SHA) for the RDK git repository."; \
+	echo "    Depends on INCLUDE_RDK=true and USE_RDK_REPO=true"; \
 	echo "RDK_MODULES_STATIC: Indicates if the RDK modules should"; \
 	echo "                    be statically linked in the linux kernel"; \
 	echo "    Optional: Applies only when INCLUDE_RDK='true'" ; \
 	echo "    Default:  false"; \
 	echo "IES_ENABLE_SHM=[true|false]:"; \
-	echo "    Enable building for RDK with IES in shared-memory mode" ; \
-	echo "    Defaults to 'true'" ; \
-	echo "    When set to false, will build IES in RPC mode" ; \
+	echo "    Enable building for RDK with IES in shared-memory or RPC mode" ; \
+	echo "    Defaults to 'false'" ; \
+	echo "    When set to true, will build IES in shared-memory mode" ; \
+	echo "    and when set to false, will build IES in RPC mode" ; \
 	echo "RDK_LTTNG_ENABLE=[true|false]:"; \
 	echo "    Enable building RDK with LTTNG enabled in user space" ; \
 	echo "    Defaults to 'false'" ; \
@@ -223,16 +267,22 @@ help:
 	echo "    Defaults to <current-dir>/axxia" ; \
 	echo "BB_IMAGE_TYPE=<image name>: Optional"; \
 	echo "    The type of image to build"; \
-	echo "    Default: axxia-image-sim" ; \
-	echo "    Other choices are: axxia-image-vcn, axxia-image-small"; \
+	echo "    Default: axxia-image-run" ; \
+	echo "    Other choices are: axxia-image-dev, axxia-image-small"; \
 	echo "SDK_INSTALL_DIR=<sdk-install-location>"; \
 	echo "    Required when 'install-sdk' is called"; \
 	echo "LINUX_VERSION=<version>: Optional:"; \
-	echo "    Default: 5.10" ; \
-	echo "    Supported versions : 5.10"; \
+	echo "    Default: v6.9" ; \
+	echo "    Supported versions : v6.9"; \
 	echo "SIMICS_VERSION=<version>" ; \
 	echo "    Optional: when INCLUDE_SIMICSFS='true'" ; \
-	echo "    Default: 6.0.88" ; \
+	echo "    Default: 7.12.00" ; \
+	echo "INCLUDE_UPDATES: Optional: Default = true" ; \
+	echo "    When set to 'true', will include meta-intel-axxia-updates Yocto"; \
+	echo "    layer with minimal changes to fix older Intel Axxia relases"; \
+	echo "META_UPDATES_URL=<URL-for-meta-intel-axxia-updates>: Optional:"; \
+	echo "    Defaults to https://github.com/axxia/meta-intel-axxia-updates.git";\
+	echo "    Required: when INCLUDE_UPDATES='true'"; \
 	echo "BB_NUMBER_THREADS=<num_threads>: Optional:"; \
 	echo "    Number of parallel threads to run"; \
 	echo "    Defaults to '24'" ; \
@@ -269,30 +319,38 @@ $(TOP)/meta-security: $(TOP)/meta-intel-axxia
 	$(call  populate,$@,$(SECURITY_URL))
 	$(call  checkout_layer_from_file,$@)
 
+$(TOP)/meta-intel-axxia-updates: $(TOP)/meta-intel-axxia-updates
+ifeq ($(INCLUDE_UPDATES),true)
+	$(call  populate,$@,$(META_UPDATES_URL))
+	$(call  checkout_rev_main,$@,$(META_AXXIA_REL))
+endif
+
 # create bitbake build
 .PHONY: build
 build: get-rdk get-simics $(LAYERS)
 		set -e ; \
                 echo "Generating local.conf in $(BLDDIR)" ; \
 		cd $(TOP); \
-		rm -rf $(BLDDIR)/conf; \
-		source $(AXXIA_REPO_NAME)/axxia-env ; \
-		source poky/oe-init-build-env $(BLDDIR) ; \
+		rm -rf $(BLDDIR)/conf ; \
+		$(call source-bb-env) ; \
+		cp -pf $(LINUX_CONF) $(TOP)/meta-intel-axxia/meta-intel-distro/recipes-kernel/linux/defconfig ; \
 		echo "PWD = $$PWD" ; \
+		sed -i s/^MACHINE[[:space:]]*=.*/MACHINE\ =\ \"$(BB_MACHINE_NAME)\"/g conf/local.conf ; \
 		sed -i s/^DISTRO[[:space:]]*=.*/DISTRO\ =\ \"$(DISTRO)\"/g conf/local.conf ; \
+		sed -i s/^MACHINE.*/MACHINE\ =\ \"$(BB_MACHINE_NAME)\"/g conf/local.conf; \
 		sed -i s/^RUNTARGET.*/RUNTARGET\ =\ \"$(RUNTARGET)\"/g conf/local.conf ; \
 		sed -i s/^BB_NUMBER_THREADS.*/BB_NUMBER_THREADS\ =\ \"$(BB_NUMBER_THREADS)\"/g conf/local.conf ; \
 		sed -i s/^PARALLEL_MAKE.*/PARALLEL_MAKE\ =\ \"$(PARALLEL_MAKE)\"/g conf/local.conf ; \
 		sed -i '/^PREFERRED_PROVIDER_virtual\/kernel/ d' conf/local.conf ; \
 		sed -i '/^PREFERRED_VERSION_linux/ d' conf/local.conf ; \
 		echo "PREFERRED_PROVIDER_virtual/kernel = \"$(PREFERRED_PROVIDER_virtual/kernel)\"" >> conf/local.conf ; \
-		echo "$(PREFERRED_VERSION_linux) = \"$(LINUX_VERSION)%\"" >> conf/local.conf ; \
+		echo "KORG_VERSION = \"$(KORG_VERSION)\"" >> conf/local.conf ; \
 		echo "RELEASE_VERSION = \"$(META_AXXIA_REL)\"" >> conf/local.conf ; \
 		echo "BB_NO_NETWORK = \"$(BB_NO_NETWORK)\"" >> conf/local.conf ; \
+		echo "DISTRO_FEATURES:append = \" multilib\"" >> conf/local.conf ; \
 		if [[ "$(INCLUDE_RDK)" == "true" ]]; then \
-			if [[ "$(INCLUDE_RDK_TOOLS)" == "true" ]]; then \
-				echo "DISTRO_FEATURES_append = \"$(DISTRO_FEATURES_append_intree)\"" >> conf/local.conf ; \
-			fi ; \
+			bitbake-layers add-layer -F $(TOP)/$(RDK_REPO_NAME) ; \
+			echo "DISTRO_FEATURES:append = \"$(DISTRO_FEATURES_append_intree)\"" >> conf/local.conf ; \
 			sed -i '/^RDK_.*._ARCHIVE/ d' conf/local.conf ; \
 			sed -i '/^RDK_.*._VERSION/ d' conf/local.conf ; \
 			RC=$(grep IES_ENABLE_SHM conf/local.conf) ; \
@@ -311,30 +369,46 @@ build: get-rdk get-simics $(LAYERS)
 			else \
 				echo "RDK_LTTNG_ENABLE = \"$(RDK_LTTNG_ENABLE)\"" >> conf/local.conf ; \
 			fi ; \
-			if [[ "$(INCLUDE_RDK_TOOLS)" == "true" ]]; then \
-				echo "RDK_TOOLS_ARCHIVE = \"file://$(RDK_SRC_PATH)/$(RDK_TOOLS_ARCHIVE)\"" >> conf/local.conf ; \
-				echo "RDK_TOOLS_VERSION = \"$(RDK_TOOLS_VERSION)\"" >> conf/local.conf ; \
+			if [[ "$(USE_RDK_REPO)" == "true" ]]; then \
+				echo "USE_RDK_REPO = \"$(USE_RDK_REPO)\"" >> conf/local.conf ; \
+				echo "RDK_REPO = \"$(RDK_REPO)\"" >> conf/local.conf ; \
+				if [[ "x$(RDK_REPO_REV)" != "x" ]]; then \
+					echo "RDK_REPO_REV = \"$(RDK_REPO_REV)\"" >> conf/local.conf ; \
+				else \
+					echo "Error: RDK_REPO_REV not set. When USE_RDK_REPO is 'true', need to set RDK_REPO_REV to either a commit SHA or tag."; \
+					exit 1; \
+				fi ; \
+			else \
+				echo "RDK_KLM_ARCHIVE = \"file://$(RDK_SRC_PATH)/$(RDK_KLM_ARCHIVE)\"" >> conf/local.conf ; \
+				echo "RDK_KLM_VERSION = \"$(RDK_KLM_VERSION)\"" >> conf/local.conf ; \
+				if [[ "$(INCLUDE_RDK_TOOLS)" == "true" ]]; then \
+					echo "RDK_TOOLS_ARCHIVE = \"file://$(RDK_SRC_PATH)/$(RDK_TOOLS_ARCHIVE)\"" >> conf/local.conf ; \
+					echo "RDK_TOOLS_VERSION = \"$(RDK_TOOLS_VERSION)\"" >> conf/local.conf ; \
+				fi ; \
 			fi ; \
-			echo "RDK_KLM_ARCHIVE = \"file://$(RDK_SRC_PATH)/$(RDK_KLM_ARCHIVE)\"" >> conf/local.conf ; \
-			echo "RDK_KLM_VERSION = \"$(RDK_KLM_VERSION)\"" >> conf/local.conf ; \
-			echo "BBLAYERS += \"$(TOP)/$(RDK_REPO_NAME)\"" >> conf/bblayers.conf; \
 		fi ; \
 		if [[ "$(INCLUDE_SIMICSFS)" = "true" ]]; then \
-                        echo "DISTRO_FEATURES_append = \" simicsfs\"" >> conf/local.conf ;\
+                        echo "DISTRO_FEATURES:append = \" simics\"" >> conf/local.conf ;\
                         echo "SIMICS_VERSION = \"$(SIMICS_VERSION)\"" >> conf/local.conf ;\
                 else \
-			sed -i /DISTRO_FEATURES_append.*simicsfs/s/^/#/g conf/local.conf; \
+                        sed -i /DISTRO_FEATURES:append.*simics/s/^/#/g conf/local.conf; \
 		fi; \
 		if [[ "$(DL_DIR)" != "" ]]; then \
 			echo "DL_DIR = \"$(DL_DIR)\"" >> conf/local.conf; \
-		fi ;
+		fi ; \
+		if [[ "$(INCLUDE_UPDATES)" == "true" ]]; then \
+			bitbake-layers add-layer -F $(TOP)/$(UPDATES_REPO_NAME); \
+		fi ; \
+		echo "MACHINE = \"$(BB_MACHINE_NAME)\"" >> conf/local.conf
 
 .PHONY: get-rdk
 get-rdk: $(LAYERS)
 ifeq ($(INCLUDE_RDK),true)
+ifeq ($(USE_RDK_REPO),false)
 	$(call check-file-exists, $(RDK_SRC_PATH)/$(RDK_KLM_ARCHIVE))
 ifeq ($(INCLUDE_RDK_TOOLS),true)
 	$(call check-file-exists, $(RDK_SRC_PATH)/$(RDK_TOOLS_ARCHIVE))
+endif
 endif
 ifeq ($(RDK_MODULES_STATIC),true)
 	(RDK_CFG=$(TOP)/$(RDK_REPO_NAME)/recipes-kernel/linux/frags/rdk-modules.cfg ; \
@@ -384,11 +458,12 @@ endif
 .PHONY: craff_gen
 craff_gen:
 ifeq ($(INCLUDE_SIMICSFS),true)
-	set -e ; \
-	cd $(BLDDIR) ; \
+	set -e ;                                    \
+	cd $(BLDDIR) ;                              \
 	CRAFF_BIN=$$(find tmp/work/*/simicsfs-client -name craff | grep linux64 | grep bin | head -n 1) ; \
-	cd $(BLDDIR)/tmp/deploy/images/axxiax86-64 ; \
-	$(BLDDIR)/$$CRAFF_BIN -o $(BB_IMAGE_TYPE)-axxiax86-64.craff $(BB_IMAGE_TYPE)-axxiax86-64.wic
+	cd $(BLDDIR)/tmp/deploy/images/$(BB_MACHINE_NAME) ; \
+	IMAGE_SUFFIX=".rootfs.wic";         \
+	$(BLDDIR)/$$CRAFF_BIN -o $(BB_IMAGE_TYPE)-$(BB_MACHINE_NAME).craff $(BB_IMAGE_TYPE)-$(BB_MACHINE_NAME)$${IMAGE_SUFFIX}
 endif
 
 clobber:
